env:
  browser: true
  es6: true
extends:
  - "plugin:react/recommended"
  - airbnb
  - eslint:recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - prettier
rules:
  {
    "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }],
    "import/prefer-default-export": "off",
    "no-console": "off",
    "prettier/prettier": "error",
  }
